### ISSUE TITLE
gender and age_group can be null

### ISSUE THREAD

**Issue by mojoaxel** [mkatenhusen/covid-19-api-backend#4]
Es kann vorkommen, dass `gender_age.gender` und `gender_age.age_group` NULL sind.
Das kommt vor weit manchmal die Daten als `unbekannt` liefern.

Ich würde vorschlagen `null` einfach zuzulassen. Alternativ kann ich auch `unbekannt` schicken.

**Comment by mojoaxel** [comment]
ganz rausfilter möchte ich die Datensätze eigentlich nicht...(auch wenn das RKI-Dashboard das momentan so macht.)

**Comment by mkatenhusen** [comment]
Ah sorry, jetzt verstehe ich es. Bitte schick in dem Falle unbekannt, null kann ich nicht zulassen, da die gender_age Relation unique_together mit den ForeignKeys age und gender hat
